name: Run Tests and Generate Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create credentials.properties
        run: |
          mkdir -p src/main/resources
          echo "validUser1=${{ secrets.VALIDUSER1 }}" > src/main/resources/credentials.properties
          echo "validPass1=${{ secrets.VALIDPASS1 }}" >> src/main/resources/credentials.properties
          echo "baseUrl=${{ secrets.BASEURL }}" >> src/main/resources/credentials.properties

      - name: Run login test to generate tokens
        run: mvn test -Dgroups=Credentials

      - name: Run tests
        run: mvn clean test
        continue-on-error: true

      - name: Generate Allure report
        run: |
          allure generate target/allure-results --clean -o target/allure-report
          ls -R target/allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
